field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  11584b12-62ab-4c6d-bd96-af95de3378b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dbe1bd8a-c52b-418f-be3b-fe46ac093d9c # Tabs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76281783-f067-4cda-918f-15094d0d043d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0554766-2af9-42fd-b382-894b109e96f4
        userCondition: null
fields:
  dbe1bd8a-c52b-418f-be3b-fe46ac093d9c: # Tabs
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tabs
    instructions: null
    name: Tabs
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1184737935
      columns:
        __assoc__:
          -
            - 236f1e3d-b5b7-48b9-9407-f06fa45d0d13 # Tab Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3807ab11-9fdf-49ac-9af0-9ca3e77892fd # Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 12ea636b-5a1f-4623-987d-16d5a681feb6 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d28b8567-1d40-4d40-8f1b-3208f4063d3b # Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_13_tabs}}'
      fieldLayout: row
      maxRows: 5
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a tab'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: tabCallout
name: 'Tab Callout'
sortOrder: 7
